
########## Configuration Features ##########

# Installer Folders #
CronicleInstallTool_ConfDir="conf"
CronicleInstallTool_FuncDir="functions"

# Configure Cronicle
# Assign Variables
Cronicle_SelectedVersion="Cronicle" # Can be 'Cronicle' or 'Cronicle-edge'
Cronicle_MainPath="/opt/cronicle"
Cronicle_ConfigPath="/opt/cronicle/conf"
Cronicle_ConfigFile="/opt/cronicle/conf/config.json"
Cronicle_BinPath="/opt/cronicle/bin"
Cronicle_ControlFile="/opt/cronicle/bin/control.sh"
Cronicle_ServiceFile="cronicle.service"

# Ssystemd Stuff #
Systemd_Dir="/etc/systemd/system"
